package sample.common.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import sample.common.dao.entity.Users;
import sample.common.dao.entity.UsersExample;

@Mapper
public interface UsersMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	long countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int deleteByPrimaryKey(Object users_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int insert(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int insertSelective(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	Users selectByPrimaryKey(Object users_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int updateByExampleSelective(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int updateByExample(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int updateByPrimaryKeySelective(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Thu Jun 05 11:17:51 JST 2025
	 */
	int updateByPrimaryKey(Users row);

	// Add Start
    Users usersSearch(Users users);
    // Add End
}