package sample.common.dao.entity;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.users_id
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    private Object users_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.email
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    private Object email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    private Object password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created_at
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.team_name
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    private Object team_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.users_id
     *
     * @return the value of public.users.users_id
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public Object getUsers_id() {
        return users_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.users_id
     *
     * @param users_id the value for public.users.users_id
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public void setUsers_id(Object users_id) {
        this.users_id = users_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.email
     *
     * @return the value of public.users.email
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public Object getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.email
     *
     * @param email the value for public.users.email
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public void setEmail(Object email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public Object getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public void setPassword(Object password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.created_at
     *
     * @return the value of public.users.created_at
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.created_at
     *
     * @param created_at the value for public.users.created_at
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.team_name
     *
     * @return the value of public.users.team_name
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public Object getTeam_name() {
        return team_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.team_name
     *
     * @param team_name the value for public.users.team_name
     *
     * @mbg.generated Wed Jun 04 14:24:07 JST 2025
     */
    public void setTeam_name(Object team_name) {
        this.team_name = team_name;
    }
}