package com.example.zikosyoukaiWeb.dao.entity;

import java.util.Date;

import lombok.Data;

@Data
public class Introductions {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.introduction_id
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private Integer introduction_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.user_id
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private String user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.name
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.kana
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private String kana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.gender
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.hobby
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private String hobby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.word
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private String word;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.created_at
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private Date created_at;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.updated_at
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	private Date updated_at;

}