package com.example.zikosyoukaiWeb.dao.entity;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.user_id
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.email
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created_at
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.team_name
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    private String team_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.user_id
     *
     * @return the value of public.users.user_id
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.user_id
     *
     * @param user_id the value for public.users.user_id
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.email
     *
     * @return the value of public.users.email
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.email
     *
     * @param email the value for public.users.email
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.created_at
     *
     * @return the value of public.users.created_at
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.created_at
     *
     * @param created_at the value for public.users.created_at
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.team_name
     *
     * @return the value of public.users.team_name
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public String getTeam_name() {
        return team_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.team_name
     *
     * @param team_name the value for public.users.team_name
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    public void setTeam_name(String team_name) {
        this.team_name = team_name == null ? null : team_name.trim();
    }
}