package com.example.zikosyoukaiWeb.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.zikosyoukaiWeb.IntroductionsForm;
import com.example.zikosyoukaiWeb.dao.entity.Introductions;
import com.example.zikosyoukaiWeb.dao.entity.IntroductionsExample;

@Mapper
public interface IntroductionsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	long countByExample(IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int deleteByExample(IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int deleteByPrimaryKey(Integer introduction_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int insert(Introductions row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int insertSelective(Introductions row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	List<Introductions> selectByExample(IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	Introductions selectByPrimaryKey(Integer introduction_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int updateByExampleSelective(@Param("row") Introductions row, @Param("example") IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int updateByExample(@Param("row") Introductions row, @Param("example") IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int updateByPrimaryKeySelective(Introductions row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Thu Jul 03 16:19:10 JST 2025
	 */
	int updateByPrimaryKey(Introductions row);

	List<Introductions> selectAll();

	// IntroductionsMapper.java
	@Select("SELECT * FROM introductions WHERE introduction_id = #{introduction_id}")
	Introductions findById(int id);

	@Update("UPDATE introductions SET name = #{name}, kana = #{kana}, gender = #{gender}, hobby = #{hobby}, word = #{word} WHERE introduction_id = #{introduction_id}")
	void update(IntroductionsForm form);

	@Delete("DELETE FROM introductions WHERE introduction_id = #{introduction_id}")
	void delete(int id);

	@Insert("""
			    INSERT INTO introductions (name, kana, gender, hobby, word)
			    VALUES (#{name}, #{kana}, #{gender}, #{hobby}, #{word}, typeHandler=com.example.zikosyoukaiWeb.StringListTypeHandler, jdbcType=VARCHAR})
			""")
	@Options(useGeneratedKeys = true, keyProperty = "introduction_id")
	void insertIntroduction(Introductions dto);

}