package com.example.zikosyoukaiWeb.dao.mapper;

import com.example.zikosyoukaiWeb.dao.entity.Introductions;
import com.example.zikosyoukaiWeb.dao.entity.IntroductionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntroductionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    long countByExample(IntroductionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int deleteByExample(IntroductionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int deleteByPrimaryKey(Integer introduction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int insert(Introductions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int insertSelective(Introductions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    List<Introductions> selectByExample(IntroductionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    Introductions selectByPrimaryKey(Integer introduction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int updateByExampleSelective(@Param("row") Introductions row, @Param("example") IntroductionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int updateByExample(@Param("row") Introductions row, @Param("example") IntroductionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int updateByPrimaryKeySelective(Introductions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.introductions
     *
     * @mbg.generated Fri Jun 20 17:52:36 JST 2025
     */
    int updateByPrimaryKey(Introductions row);
}