package com.example.zikosyoukaiWeb.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.zikosyoukaiWeb.dao.entity.Users;
import com.example.zikosyoukaiWeb.dao.entity.UsersExample;

@Mapper
public interface UsersMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	long countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int deleteByPrimaryKey(String user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int insert(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int insertSelective(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	Users selectByPrimaryKey(String user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int updateByExampleSelective(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int updateByExample(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int updateByPrimaryKeySelective(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Tue Jul 01 17:07:05 JST 2025
	 */
	int updateByPrimaryKey(Users row);

	int countUsers(String username);
}